### ISSUE TITLE
SVG export on REPL website

### ISSUE THREAD

**Issue by pwab** [gera2ld/markmap-lib#22]
A few days ago I was able to export the mindmap as SVG on the 'Try Markmap' Website:
https://markmap.js.org/repl

Was this feature removed? Because now it is only possible to export as interactive website.

**Comment by gera2ld** [comment]
Yes, I removed it because the exported SVG is buggy when prismJS or mathJax is enabled. In that case external styles are required and sometimes JavaScript is also needed so a pure SVG is obviously not capable for it.

What's your use case for SVG export? Maybe we can find a way to support it in certain situations.

**Comment by pwab** [comment]
Yeah I tried it with one or two commits before and I noticed some problems with SVG export. I can see your point and the interactive html is perfect for most cases.

My use case was to send a picture of the generated mindmap to a friend of mine 😅. It was a huge mindmap so a screenshot wasn't an option. A PNG export of the canvas would be nice - but it would need some well chosen resolution to make it useful for big mindmaps.

Also SVG has the advantage to be changeable after export when I don't need interactivity but only want to print it or something like that.

**Comment by r37r0m0d3l** [comment]
Oh no. Can you put button back? And mark it "buggy" 🐛? The thing was **VERY** useful. Maybe I can do some fixes, if you can't find time for it.

**Comment by r37r0m0d3l** [comment]
No news is good news?

**Comment by gera2ld** [comment]
It's back now.
